#+title: bisos.csSeed:  Commands Services Seeds and Plants
#+DATE: <2026-01-01 Thu 13:11>
#+AUTHOR: Mohsen BANAN
#+OPTIONS: toc:4

#+BEGIN: b:org:pypi:readme/topControls :pkgName "csSeed" :comment "basic"

# TopControls don't apply to pypi.org documentation.

#+END:

* Overview

/bisos.csSeed/ provides general facilities for creation of arget Oriented
Command-Services (tocs) Modules.

In this model Targets are collections of accessible Managed Objects (MOs). Target-Modules
are Python modules which are aware of the Target's set of MOs

bisos.csSeed is a python package that uses the  [[https://github.com/bisos-pip/pycs][PyCS-Framework]].


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#part-of-bisos-----bystar-internet-services-operating-system][Part of BISOS --- ByStar Internet Services Operating System]]
- [[#installation][Installation]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
  - [[#post-installation-basic-testing][Post Installation Basic Testing]]
- [[#usage][Usage]]
  - [[#local-usage-system-command-line][Local Usage (system command-line)]]
- [[#documentation-and-blee-panels][Documentation and Blee-Panels]]
  - [[#bisoscsseed-blee-panels][bisos.csSeed Blee-Panels]]
- [[#support][Support]]
- [[#planned-improvements][Planned Improvements]]

* Part of BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.\\
*BISOS* is a foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is
described as a cure for losses of autonomy and privacy in a book titled: [[https://github.com/bxplpc/120033][Nature
of Polyexistentials]]. /bisos.csSeed/ is part of BISOS.


* Installation

The sources for the bisos.csSeed pip package are maintained at:
https://github.com/bisos-pip/csSeed.

The bisos.csSeed pip package is available at PYPI as
https://pypi.org/project/bisos.csSeed

You can install bisos.csSeed with pip or pipx.

** Installation With pip

If you need access to bisos.csSeed as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.csSeed
#+end_src

** Installation With pipx

If you only need access to bisos.csSeed on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.csSeed
#+end_src

** Post Installation Basic Testing

After the installation, run some basic tests:

#+begin_src bash
csSeed.cs
csSeed networking.interfaces.lo.bindings
#+end_src


* Usage

** Local Usage (system command-line)

=csSeed.cs= does the equivalent of csSeed.

#+begin_src bash
bin/csSeed.cs
#+end_src


* Documentation and Blee-Panels

bisos.csSeed is part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in the form of Blee-Panels.
Additional information is also available in: [[http://www.by-star.net/PLPC/180047]]

** bisos.csSeed Blee-Panels

bisos.csSeed Blee-Panles are in ./panels directory.
From within Blee and BISOS these panles are accessible under the
Blee "Panels" menu.

See [[file:./py3/panels/_nodeBase_/fullUsagePanel-en.org]] for a starting point.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


* Planned Improvements

- Enumerate applicabilities: telecom/SON, datacenter, CMIP-MOs
- py3/bisos/csSeed/tocsModule_csu.py

# Local Variables:
# eval: (setq-local toc-org-max-depth 4)
# End:
